### ISSUE TITLE
Selections in editor from using Search in Workspace functionality are light colored

### ISSUE THREAD

**Issue by unphased** [jbrennan/xcode4themes#5]
This might be a limitation of XCode itself (I am currently on 4.3.3 and intend to update it soon) but this makes some of the dark themes harder to use, because the text is nearly white and blends into these type of selections. 

![selected text almost invisible](http://i.imgur.com/KCb6x.png)

**Comment by unphased** [comment]
To provide some further information: It appears as though the color (which we have not found a way to adjust) is the color of selections which are inactive. Select something then click outside the buffer.

**Comment by jbrennan** [comment]
Yeah I'm not really sure how to resolve this one as I don't use dark themes myself. They kill my eyes. It's very likely a limitation of Xcode though.
